[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_src_filter = +<PIXI_CYD_V8_LIFE_HTTPS_BLE.ino> -<extras/>
lib_deps =
  lovyan03/LovyanGFX
  h2zero/NimBLE-Arduino @ ^2.3.6
