package com.pixilife.android;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.camera2.*;import android.media.Image;import android.media.ImageReader;import android.util.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.ByteBuffer;import java.util.*;import org.json.*;

public class CameraActivity extends Activity {
 private TextureView preview;private TextView status;private CameraDevice camera;private CameraCaptureSession session;private ImageReader reader;private String cameraId;private boolean front=true;private HandlerThread thread;private Handler handler;private String question="Describe brevemente y con precisión lo que ves. No inventes detalles.";
 @Override public void onCreate(Bundle b){super.onCreate(b);question=getIntent().getStringExtra("question")!=null?getIntent().getStringExtra("question"):question;ui();if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},7);}
 private void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(7,11,17));status=new TextView(this);status.setText("CÁMARA ACTIVA · las imágenes no se guardan");status.setTextColor(Color.WHITE);status.setPadding(18,18,18,18);root.addView(status);preview=new TextureView(this);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);Button swap=b("Cambiar cámara"),look=b("Analizar imagen"),close=b("Cerrar");bar.addView(swap);bar.addView(look);bar.addView(close);root.addView(bar);setContentView(root);swap.setOnClickListener(v->{front=!front;closeCamera();openCamera();});look.setOnClickListener(v->capture());close.setOnClickListener(v->finish());preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){openCamera();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});}
 private Button b(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));return b;}
 @Override protected void onResume(){super.onResume();stopService(new Intent(this,LiveVisionService.class));thread=new HandlerThread("PixiCamera");thread.start();handler=new Handler(thread.getLooper());if(preview.isAvailable())openCamera();}
 @Override protected void onPause(){closeCamera();if(thread!=null)thread.quitSafely();if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED){Intent i=new Intent(this,LiveVisionService.class).setAction(LiveVisionService.ACTION_START);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}super.onPause();}
 private void openCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)return;try{CameraManager m=(CameraManager)getSystemService(CAMERA_SERVICE);cameraId=null;for(String id:m.getCameraIdList()){Integer f=m.getCameraCharacteristics(id).get(CameraCharacteristics.LENS_FACING);if(f!=null&&f==(front?CameraCharacteristics.LENS_FACING_FRONT:CameraCharacteristics.LENS_FACING_BACK)){cameraId=id;break;}}if(cameraId==null)return;reader=ImageReader.newInstance(1280,720,android.graphics.ImageFormat.JPEG,2);reader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im==null)return;ByteBuffer buf=im.getPlanes()[0].getBuffer();byte[] data=new byte[buf.remaining()];buf.get(data);im.close();analyze(data);},handler);m.openCamera(cameraId,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startPreview();}public void onDisconnected(CameraDevice c){c.close();camera=null;}public void onError(CameraDevice c,int e){c.close();camera=null;runOnUiThread(()->status.setText("Error de cámara: "+e));}},handler);}catch(Exception e){status.setText("No se pudo abrir la cámara: "+e.getMessage());}}
 private void startPreview(){try{SurfaceTexture t=preview.getSurfaceTexture();t.setDefaultBufferSize(1280,720);Surface s=new Surface(t);camera.createCaptureSession(Arrays.asList(s,reader.getSurface()),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession x){session=x;try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(s);b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);session.setRepeatingRequest(b.build(),null,handler);}catch(Exception e){}}public void onConfigureFailed(CameraCaptureSession x){runOnUiThread(()->status.setText("No se pudo iniciar la vista previa"));}},handler);}catch(Exception e){status.setText("Error de vista previa: "+e.getMessage());}}
 private void capture(){if(camera==null||session==null)return;status.setText("Analizando imagen actual…");try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);b.addTarget(reader.getSurface());b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);session.capture(b.build(),null,handler);}catch(Exception e){status.setText("No se pudo capturar: "+e.getMessage());}}
 private void analyze(byte[] jpeg){new Thread(()->{HttpURLConnection c=null;try{SharedPreferences p=getSharedPreferences("pixi",MODE_PRIVATE);URL u=new URL(p.getString("worker_url","https://pixi-openai.gabostorecodex.workers.dev")+"/vision");c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(15000);c.setReadTimeout(45000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("X-Pixi-Token",p.getString("access_token","Gabo@22622"));c.setDoOutput(true);JSONObject o=new JSONObject();o.put("question",question);o.put("image","data:image/jpeg;base64,"+android.util.Base64.encodeToString(jpeg,android.util.Base64.NO_WRAP));try(OutputStream out=c.getOutputStream()){out.write(o.toString().getBytes("UTF-8"));}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());String res=read(in);JSONObject j=new JSONObject(res);String answer=j.optString("reply",j.optString("error","No recibí una descripción visual."));runOnUiThread(()->{status.setText(answer);Intent i=new Intent(CameraActivity.this,ConversationService.class).setAction(ConversationService.ACTION_SPEAK).putExtra("text",answer);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);});}catch(Exception e){String msg=e.getMessage();runOnUiThread(()->status.setText("Visión no disponible: "+msg));}finally{if(c!=null)c.disconnect();}}).start();}
 private String read(InputStream in)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(in,"UTF-8"));StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}
 private void closeCamera(){try{if(session!=null)session.close();if(camera!=null)camera.close();if(reader!=null)reader.close();}catch(Exception ignored){}session=null;camera=null;reader=null;}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openCamera();else status.setText("Cámara denegada. Puedes habilitarla en el Centro de permisos.");}
}
