package com.pixilife.android;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.ImageFormat;import android.hardware.camera2.*;import android.media.*;import android.os.*;import android.view.Surface;import java.io.*;import java.nio.ByteBuffer;import java.util.*;
public class LiveVisionService extends Service {
 public static final String ACTION_START="com.pixilife.android.VISION_START",ACTION_STOP="com.pixilife.android.VISION_STOP";private HandlerThread thread;private Handler h;private CameraDevice camera;private CameraCaptureSession session;private ImageReader reader;
 @Override public void onCreate(){super.onCreate();NotificationChannel c=new NotificationChannel("pixi_vision","Visión continua de PIXI",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);thread=new HandlerThread("PixiLiveVision");thread.start();h=new Handler(thread.getLooper());}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&ACTION_STOP.equals(i.getAction())){stopSelf();return START_NOT_STICKY;}Notification n=new Notification.Builder(this,"pixi_vision").setSmallIcon(android.R.drawable.ic_menu_camera).setContentTitle("PIXI está viendo").setContentText("Cámara activa · último fotograma local").setOngoing(true).build();if(Build.VERSION.SDK_INT>=29)startForeground(18,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_CAMERA);else startForeground(18,n);open();return START_STICKY;}
 private void saveFrame(byte[] data){try{File tmp=new File(getFilesDir(),"latest_vision.jpg.tmp"),dst=new File(getFilesDir(),"latest_vision.jpg");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(data);}if(dst.exists())dst.delete();tmp.renameTo(dst);}catch(IOException ignored){}}
 private void open(){if(camera!=null)return;if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){stopSelf();return;}try{CameraManager m=getSystemService(CameraManager.class);String id=null;for(String x:m.getCameraIdList()){Integer facing=m.getCameraCharacteristics(x).get(CameraCharacteristics.LENS_FACING);if(facing!=null&&facing==CameraCharacteristics.LENS_FACING_FRONT){id=x;break;}}if(id==null)return;reader=ImageReader.newInstance(640,480,ImageFormat.JPEG,2);reader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im==null)return;ByteBuffer b=im.getPlanes()[0].getBuffer();byte[] data=new byte[b.remaining()];b.get(data);im.close();saveFrame(data);},h);m.openCamera(id,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startCapture();}public void onDisconnected(CameraDevice c){c.close();camera=null;}public void onError(CameraDevice c,int e){c.close();camera=null;}},h);}catch(Exception e){stopSelf();}}
 private void startCapture(){try{Surface s=reader.getSurface();camera.createCaptureSession(Collections.singletonList(s),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession x){session=x;captureLoop();}public void onConfigureFailed(CameraCaptureSession x){}},h);}catch(Exception e){stopSelf();}}
 private void captureLoop(){if(camera==null||session==null)return;try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(reader.getSurface());session.capture(b.build(),new CameraCaptureSession.CaptureCallback(){@Override public void onCaptureCompleted(CameraCaptureSession s,CaptureRequest r,TotalCaptureResult x){h.postDelayed(()->captureLoop(),5000);}},h);}catch(Exception e){h.postDelayed(()->captureLoop(),5000);}}
 private void closeCamera(){try{if(session!=null)session.close();if(camera!=null)camera.close();if(reader!=null)reader.close();}catch(Exception ignored){}session=null;camera=null;reader=null;}
 @Override public void onDestroy(){closeCamera();if(thread!=null)thread.quitSafely();super.onDestroy();}public android.os.IBinder onBind(Intent i){return null;}
}
