package com.pixilife.android;

import android.Manifest; import android.app.Activity; import android.content.*; import android.content.pm.PackageManager; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.text.InputType; import android.view.*; import android.widget.*;

public class MainActivity extends Activity {
 private static final int PERMISSIONS=42; private final int bg=Color.rgb(7,11,17), card=Color.rgb(17,25,35), blue=Color.rgb(30,115,232), pink=Color.rgb(216,47,100); private SharedPreferences prefs; private TextView bt,mood,clock,net,heard,reply,help; private EditText url,token,text,name; private Button continuous;
 private Button voiceToggle;
 private final BroadcastReceiver events=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String t=i.getStringExtra("type"),v=i.getStringExtra("value");if("reply".equals(t))reply.setText(v);else if("heard".equals(t))heard.setText(v);else if("voice".equals(t)&&voiceToggle!=null)voiceToggle.setText("on".equals(v)?"🔊 Voz activada":"🔇 Voz desactivada");else if("status".equals(t)){help.setText(v);bt.setText(v!=null&&v.toLowerCase().contains("conect")?"BLE: PIXI conectada":"BLE: "+v);}}};
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("pixi",MODE_PRIVATE);ui();permissions();}
 private void ui(){ScrollView s=new ScrollView(this);s.setBackgroundColor(bg);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,24);
  ImageView logoImage=new ImageView(this);logoImage.setImageResource(R.drawable.pixi_logo);logoImage.setScaleType(ImageView.ScaleType.CENTER_INSIDE);LinearLayout.LayoutParams logoLp=new LinearLayout.LayoutParams(-1,150);logoImage.setLayoutParams(logoLp);root.addView(logoImage); TextView logo=label("Pixi Voice",28,Color.WHITE);logo.setGravity(Gravity.CENTER);logo.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(logo);root.addView(label("OpenRouter Mistral + Bluetooth",15,Color.rgb(145,166,192))); LinearLayout pills=new LinearLayout(this);pills.setOrientation(LinearLayout.HORIZONTAL);bt=pill("BLE: desconectado");mood=pill("Pixi: --");clock=pill("--:--");net=pill("En linea");pills.addView(bt);pills.addView(mood);pills.addView(clock);pills.addView(net);root.addView(pills);
  LinearLayout ble=card();ble.addView(label("CONEXION BLE",18,Color.WHITE));Button connect=button("🔵 CONECTAR A PIXI",blue);ble.addView(connect);connect.setOnClickListener(v->act(ConversationService.ACTION_SCAN,null));ble.addView(label("En Android se usa Bluetooth nativo y reconexion automatica. Elige PIXI cuando aparezca.",12,Color.rgb(139,160,187)));root.addView(ble);
  LinearLayout ai=card();ai.addView(label("⚡ OpenRouter · Mistral Small 3.2",18,Color.WHITE));ai.addView(label("Conexion segura configurada automaticamente. La URL tecnica y el token quedan protegidos y no se muestran.",13,Color.rgb(139,160,187)));url=edit("URL",false);url.setText(prefs.getString("worker_url","https://pixi-openai.gabostorecodex.workers.dev"));url.setVisibility(View.GONE);token=edit("Token",true);token.setText(prefs.getString("access_token","Gabo@22622"));token.setVisibility(View.GONE);Button save=button("Verificar conexion",blue);ai.addView(save);save.setOnClickListener(v->save());root.addView(ai);
  LinearLayout talk=card();continuous=button("🔁 Activar conversacion continua",pink);talk.addView(continuous);continuous.setOnClickListener(v->{save();act(ConversationService.ACTION_CONTINUOUS,null);continuous.setText("⏹ Detener conversacion continua");});heard=label("Tu: ...",16,Color.WHITE);reply=label("Pixi: ...",16,Color.rgb(255,220,245));talk.addView(heard);talk.addView(reply);help=label("La conversacion escucha, responde y vuelve a escuchar.",12,Color.rgb(139,160,187));talk.addView(help);root.addView(talk);
  LinearLayout write=card();write.addView(label("⌨ Escribir",18,Color.WHITE));text=edit("Escribe algo para Pixi",false);write.addView(text);Button send=button("Enviar",blue);write.addView(send);send.setOnClickListener(v->{String q=text.getText().toString().trim();if(!q.isEmpty()){heard.setText("Tu: "+q);act(ConversationService.ACTION_MESSAGE,q);text.setText("");}});root.addView(write);
  LinearLayout voice=card();voice.addView(label("🎀 Voz",18,Color.WHITE));voice.addView(label("Preset: Tierna · tono alto · velocidad suave",14,Color.LTGRAY));voiceToggle=button(prefs.getBoolean("voice_enabled",true)?"🔊 Voz activada":"🔇 Voz desactivada",blue);voice.addView(voiceToggle);voiceToggle.setOnClickListener(v->act(ConversationService.ACTION_VOICE_TOGGLE,null));Button test=button("🔊 Probar voz",blue);voice.addView(test);test.setOnClickListener(v->act(ConversationService.ACTION_SPEAK,"¡Holii! Soy Pixi. Pi pi."));root.addView(voice);
  LinearLayout profile=card();profile.addView(label("🧠 Perfil",18,Color.WHITE));name=edit("Tu nombre",false);profile.addView(name);Button sp=button("Guardar en Pixi",blue);profile.addView(sp);sp.setOnClickListener(v->{act(ConversationService.ACTION_MESSAGE,"Mi nombre es "+name.getText().toString());});root.addView(profile);
  LinearLayout faces=card();faces.addView(label("😊 Caras y expresiones",18,Color.WHITE));String[][] fs={{"😊 Feliz","happy"},{"😍 Cariñosa","love"},{"🤔 Pensando","thinking"},{"😠 Molesta","angry"},{"😴 Cansada","sleepy"},{"🤖 Robot","robot"},{"🙄 Harta","annoyed"},{"🤬 Furiosa","furious"},{"😏 Sarcastica","sarcasm"},{"😒 Sin gracia","unimpressed"},{"😳 Avergonzada","embarrassed"},{"😌 Orgullosa","proud"},{"😜 Juguetona","playful"},{"😵 Mareada","dizzy"},{"😱 Impactada","shocked"},{"🤨 Sospechosa","suspicious"},{"😬 Nerviosa","nervous"},{"😮‍💨 Aliviada","relieved"},{"😤 Grunona","grumpy"},{"😈 Traviesa","mischievous"},{"😐 Seca","deadpan"},{"🤩 Estrellada","starry"},{"🥹 Llora feliz","happycry"},{"☹ Puchero","pout"},{"😛 Lengua","tongue"},{"👾 Glitch","glitch"},{"🖕 Fuck you","middlefinger"},{"🤘 Rebelde","rebel"}};for(String[] f:fs){Button x=button(f[0],Color.rgb(26,41,60));faces.addView(x);x.setOnClickListener(v->act(ConversationService.ACTION_FACE,f[1]));}root.addView(faces);
  LinearLayout tools=card();tools.addView(label("Memoria, alarmas, visión y permisos",18,Color.WHITE));Button memories=button("Memoria de Pixi",blue);tools.addView(memories);memories.setOnClickListener(v->startActivity(new Intent(this,MemoryActivity.class)));Button alarms=button("Abrir alarmas",pink);tools.addView(alarms);alarms.setOnClickListener(v->startActivity(new Intent(this,AlarmActivity.class)));Button camera=button("Abrir ojos de PIXI (cámara)",pink);tools.addView(camera);camera.setOnClickListener(v->startActivity(new Intent(this,CameraActivity.class)));Button permissionCenter=button("Centro de permisos",blue);tools.addView(permissionCenter);permissionCenter.setOnClickListener(v->startActivity(new Intent(this,PermissionCenterActivity.class)));LinearLayout gaze=new LinearLayout(this);String[][] gs={{"Izquierda","-1:0"},{"Centro","0:0"},{"Derecha","1:0"}};for(String[] g:gs){Button gb=button(g[0],Color.rgb(26,41,60));gaze.addView(gb);gb.setOnClickListener(v->act(ConversationService.ACTION_GAZE,g[1]));}tools.addView(gaze);root.addView(tools);
  root.addView(label("La app puede funcionar en segundo plano con notificacion activa. Android puede detener el microfono si fuerzas el cierre.",12,Color.rgb(139,160,187)));s.addView(root);setContentView(s);}
 private TextView label(String v,int z,int c){TextView t=new TextView(this);t.setText(v);t.setTextSize(z);t.setTextColor(c);t.setPadding(0,8,0,8);return t;}private TextView pill(String v){TextView t=label(v,12,Color.WHITE);t.setPadding(12,8,12,8);return t;}private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(16,12,16,16);GradientDrawable g=new GradientDrawable();g.setColor(card);g.setCornerRadius(22);l.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,10,0,0);l.setLayoutParams(p);return l;}private EditText edit(String h,boolean secret){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.GRAY);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setPadding(12,5,12,5);if(secret)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}private Button button(String v,int c){Button b=new Button(this);b.setText(v);b.setTextColor(Color.WHITE);b.setTextSize(15);GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(15);b.setBackground(g);return b;}private void save(){prefs.edit().putString("worker_url",url.getText().toString().trim()).putString("access_token",token.getText().toString().trim()).apply();help.setText("Conexion guardada");}private void act(String a,String q){Intent i=new Intent(this,ConversationService.class).setAction(a);if(q!=null)i.putExtra("text",q);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}private void permissions(){new AndroidPermissionManager(this).requestAll();}@Override protected void onResume(){super.onResume();registerReceiver(events,new IntentFilter(ConversationService.EVENT),Build.VERSION.SDK_INT>=33?RECEIVER_NOT_EXPORTED:0);}@Override protected void onPause(){super.onPause();try{unregisterReceiver(events);}catch(Exception e){}}
}
