package com.pixilife.android;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;
public class MemoryActivity extends Activity {
 private static final int EXPORT=71,IMPORT=72;private MemoryManager manager;private BackupManager backups;private LinearLayout list;private EditText search;
 @Override public void onCreate(Bundle state){super.onCreate(state);manager=new MemoryManager(this);backups=new BackupManager(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,24,24,24);root.setBackgroundColor(Color.rgb(7,11,17));TextView title=text("MEMORIA DE PIXI",26);root.addView(title);search=new EditText(this);search.setHint("Buscar recuerdos");search.setTextColor(Color.WHITE);root.addView(search);String[] names={"Buscar","Backup cifrado","Restaurar backup","Exportar JSON","Importar JSON"};LinearLayout buttons=new LinearLayout(this);for(String n:names){Button b=new Button(this);b.setText(n);buttons.addView(b,new LinearLayout.LayoutParams(0,-2,1));if(n.equals("Buscar"))b.setOnClickListener(v->render(search.getText().toString()));else if(n.startsWith("Backup"))b.setOnClickListener(v->backup());else if(n.startsWith("Restaurar"))b.setOnClickListener(v->restore());else if(n.startsWith("Exportar"))b.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").putExtra(Intent.EXTRA_TITLE,"pixi-memory.json"),EXPORT));else b.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json"),IMPORT));}root.addView(buttons);ScrollView scroll=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render("");}
 private TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.WHITE);t.setPadding(8,8,8,8);return t;}
 private void render(String term){list.removeAllViews();JSONArray a=term.trim().isEmpty()?manager.listMemories():manager.searchMemory(term.trim());for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;TextView t=text((m.optBoolean("important")?"IMPORTANTE · ":"")+m.optString("content"),15);list.addView(t);Button d=new Button(this);d.setText("Eliminar");long id=m.optLong("id");d.setOnClickListener(v->{manager.deleteMemory(id);render(search.getText().toString());});list.addView(d);}}
 private void backup(){try{backups.backup();Toast.makeText(this,"Backup cifrado creado",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void restore(){try{int n=backups.restore();Toast.makeText(this,n+" recuerdos restaurados",Toast.LENGTH_SHORT).show();render("");}catch(Exception e){Toast.makeText(this,"No existe backup válido",Toast.LENGTH_LONG).show();}}
 @Override protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(code!=RESULT_OK||data==null)return;try{if(r==EXPORT){try(OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write(manager.exportMemory().getBytes(StandardCharsets.UTF_8));}}else if(r==IMPORT){StringBuilder s=new StringBuilder();try(BufferedReader b=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(data.getData()),StandardCharsets.UTF_8))){String l;while((l=b.readLine())!=null)s.append(l);}manager.importMemory(s.toString());render("");}}catch(Exception e){Toast.makeText(this,"Error: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
}
