package com.pixilife.android;
import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.provider.CalendarContract;import android.database.Cursor;import android.os.*;import java.util.*;import java.util.regex.*;
public class VoiceCommandReceiver extends BroadcastReceiver {
 private static long token;
 @Override public void onReceive(Context c,Intent i){if(!"heard".equals(i.getStringExtra("type")))return;String text=i.getStringExtra("value");if(text==null)return;long mine=++token;new Handler(Looper.getMainLooper()).postDelayed(()->{if(mine==token)process(c.getApplicationContext(),text);},1800);}
 private static void process(Context c,String original){String t=original.toLowerCase(Locale.ROOT);Matcher name=Pattern.compile("(?:me llamo|mi nombre es)\\s+([\\p{L}][\\p{L} '-]{0,38})",Pattern.CASE_INSENSITIVE).matcher(original.trim());if(name.find()){String n=name.group(1).trim();Intent save=new Intent(c,ConversationService.class).setAction(ConversationService.ACTION_NAME).putExtra("text",n);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(save);else c.startService(save);return;}if(t.contains("alarma")){TimeValue v=time(t);if(v!=null){Calendar when=date(t,v);int id=(int)(when.getTimeInMillis()/60000L);AlarmReceiver.scheduleAt(c,id,when.getTimeInMillis(),"Alarma de PIXI");c.getSharedPreferences("alarms",Context.MODE_PRIVATE).edit().putInt("hour",v.h).putInt("minute",v.m).putInt("days",0).putString("text","Alarma de PIXI").putLong("next",when.getTimeInMillis()).apply();answer(c,String.format(Locale.getDefault(),"Alarma puesta para %02d:%02d.",v.h,v.m));return;}}
  if((t.contains("calendario")||t.contains("evento")||t.startsWith("agrega ")||t.startsWith("añade "))&&c.checkSelfPermission(Manifest.permission.WRITE_CALENDAR)==PackageManager.PERMISSION_GRANTED){TimeValue v=time(t);if(v!=null)addCalendar(c,original,t,v);}}
 private static TimeValue time(String t){Matcher m=Pattern.compile("(?:a las?|para las?)\\s*(\\d{1,2})(?:[:.]|( y ))?(\\d{2})?").matcher(t);if(!m.find())return null;int h=Integer.parseInt(m.group(1)),min=m.group(3)==null?0:Integer.parseInt(m.group(3));if((t.contains("tarde")||t.contains("noche"))&&h<12)h+=12;if(t.contains("mañana")&&t.contains("de la mañana")&&h==12)h=0;if(h>23||min>59)return null;return new TimeValue(h,min);}
 private static Calendar date(String t,TimeValue v){Calendar c=Calendar.getInstance();if(t.contains("mañana")&&!t.contains("de la mañana"))c.add(Calendar.DAY_OF_YEAR,1);c.set(Calendar.HOUR_OF_DAY,v.h);c.set(Calendar.MINUTE,v.m);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);if(!t.contains("hoy")&&!t.contains("mañana")&&c.before(Calendar.getInstance()))c.add(Calendar.DAY_OF_YEAR,1);return c;}
 private static void addCalendar(Context c,String original,String lower,TimeValue v){long cal=-1;try(Cursor x=c.getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{CalendarContract.Calendars._ID},CalendarContract.Calendars.VISIBLE+"=1",null,null)){if(x!=null&&x.moveToFirst())cal=x.getLong(0);}catch(Exception ignored){}if(cal<0){answer(c,"No encontré un calendario activo en el teléfono.");return;}Calendar at=date(lower,v);ContentValues values=new ContentValues();values.put(CalendarContract.Events.CALENDAR_ID,cal);values.put(CalendarContract.Events.TITLE,original.replaceFirst("(?i)^(agrega|añade|pon)\\s+", ""));values.put(CalendarContract.Events.DTSTART,at.getTimeInMillis());values.put(CalendarContract.Events.DTEND,at.getTimeInMillis()+3600000);values.put(CalendarContract.Events.EVENT_TIMEZONE,TimeZone.getDefault().getID());try{c.getContentResolver().insert(CalendarContract.Events.CONTENT_URI,values);answer(c,String.format(Locale.getDefault(),"Evento agregado al calendario para %02d:%02d.",v.h,v.m));}catch(Exception e){answer(c,"No pude agregar el evento al calendario.");}}
 private static void answer(Context c,String s){c.sendBroadcast(new Intent(ConversationService.EVENT).setPackage(c.getPackageName()).putExtra("type","reply").putExtra("value",s));Intent i=new Intent(c,ConversationService.class).setAction(ConversationService.ACTION_SPEAK).putExtra("text",s);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}
 private static class TimeValue{final int h,m;TimeValue(int h,int m){this.h=h;this.m=m;}}
}
